name: PHP Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, json, pdo, pdo_mysql

      - name: Update Composer
        run: composer self-update

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Dump Autoload
        run: composer dump-autoload

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit